services:
  - type: web
    name: stock-api
    env: python
    plan: free
    buildCommand: pip install -r pycharm_project/requirements.txt
    startCommand: gunicorn portal.app:app
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://evgiofir1:Y5oJ5ka4PNyw16rg@stockcluster.egw5thu.mongodb.net/stockdb?retryWrites=true&w=majority&appName=StockCluster
